# Generated by Django 4.2.7 on 2023-11-29 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
